namespace DirStat.App.Localization;

/// <summary>
/// The string catalogues. English is the reference: every key exists here, and a lookup that
/// misses in another language falls back to this table before falling back to the key itself.
/// </summary>
public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        // ---------------------------------------------------------------- common
        ["Common.Cancel"] = "Cancel",
        ["Common.Continue"] = "Continue",
        ["Common.Back"] = "Back",
        ["Common.Clear"] = "Clear",
        ["Common.Apply"] = "Apply",
        ["Common.Add"] = "Add",
        ["Common.Remove"] = "Remove",
        ["Common.Files"] = "Files",
        ["Common.Folders"] = "Folders",
        ["Common.Name"] = "Name",
        ["Common.Size"] = "Size",
        ["Common.Share"] = "SHARE",
        ["Common.Items"] = "Items",
        ["Common.Modified"] = "Modified",
        ["Common.Dash"] = "—",

        // ---------------------------------------------------------------- window
        ["Window.Theme"] = "Switch theme",
        ["Window.Language"] = "Language",
        ["Window.Minimise"] = "Minimise",
        ["Window.Maximise"] = "Maximise",
        ["Window.Close"] = "Close",
        ["Window.About"] = "About DirStat",

        // ----------------------------------------------------------------- about
        ["About.Title"] = "DirStat",
        ["About.Tagline"] = "Find out where your disk space went, on any of the three platforms.",
        ["About.MadeBy"] = "Made by",
        ["About.Version"] = "Version",
        ["About.Licence"] = "Licence",
        ["About.LicenceValue"] = "MIT — free to use, change and share.",
        ["About.BuiltWith"] = "Built with",
        ["About.System"] = "System",
        ["About.Thanks"] = "Thanks to WinDirStat, QDirStat and SpaceSniffer, which showed what this kind of tool should do.",
        ["About.Copy"] = "Copy details",
        ["About.Copied"] = "Copied",
        ["About.Close"] = "Close",

        // --------------------------------------------------------------- volumes
        ["Volumes.Title"] = "Where did your space go?",
        ["Volumes.Subtitle"] = "Pick a drive or folder. DirStat maps every byte and shows you what is worth deleting.",
        ["Volumes.Drives"] = "DRIVES",
        ["Volumes.FreeOf"] = "free of",
        ["Volumes.OrFolder"] = "OR A SPECIFIC FOLDER",
        ["Volumes.ChooseFolders"] = "Choose folders…",
        ["Volumes.ChooseHint"] = "You can select more than one — they are scanned together.",
        ["Volumes.Recent"] = "RECENT",
        ["Volumes.Compare"] = "Compare with a snapshot",

        // ------------------------------------------------------------------ scan
        ["Scan.Title"] = "Scanning",
        ["Scan.Files"] = "FILES",
        ["Scan.Folders"] = "FOLDERS",
        ["Scan.TotalSize"] = "TOTAL SIZE",
        ["Scan.Elapsed"] = "ELAPSED",
        ["Scan.Throughput"] = "THROUGHPUT",
        ["Scan.CurrentFolder"] = "CURRENT FOLDER",
        ["Scan.Cancel"] = "Cancel scan",
        ["Scan.CancelHint"] = "Cancelling still shows everything found so far.",
        ["Scan.FilesPerSecond"] = "{0} files/s",
        ["Scan.Locations"] = "{0} locations",

        // --------------------------------------------------------------- results
        ["Results.Drives"] = "Drives",
        ["Results.BackToDrives"] = "Back to drives",
        ["Results.FilterWatermark"] = "Filter: try  *.mp4  >100mb  after:2025-01-01",
        ["Results.FilterTooltip"] = "Combine terms: plain text matches names, *.ext matches types,\n>100mb and <1gb bound size, after: and before: bound dates.",
        ["Results.Duplicates"] = "Duplicates",
        ["Results.DuplicatesTooltip"] = "Find files and folders you have more than one copy of",
        ["Results.Insights"] = "Insights",
        ["Results.InsightsTooltip"] = "Stale files, empty folders and rebuildable caches",
        ["Results.ZoomOut"] = "Zoom out one level",
        ["Results.Rescan"] = "Rescan the selected folder (F5)",
        ["Results.Options"] = "Options",
        ["Results.Folders"] = "FOLDERS",
        ["Results.Treemap"] = "TREEMAP",
        ["Results.Sunburst"] = "SUNBURST",
        ["Results.ChartHint"] = "click to select  ·  double-click to zoom  ·  arrows to walk",
        ["Results.FileTypes"] = "FILE TYPES",
        ["Results.ClickToIsolate"] = "click to isolate",
        ["Results.ExportCsv"] = "Export CSV",
        ["Results.ExportJson"] = "JSON",
        ["Results.ExportImage"] = "Save image",
        ["Results.ExportImageTooltip"] = "Save the current chart as a PNG",
        ["Results.ToggleChart"] = "Switch between treemap and sunburst",
        ["Results.SaveSnapshot"] = "Save snapshot",
        ["Results.SaveSnapshotTooltip"] = "Store this scan so a later one can be compared against it",
        ["Results.NoExtension"] = "(no extension)",
        ["Results.FreeSpace"] = "Free space",
        ["Results.UnknownSpace"] = "Unknown",

        // ------------------------------------------------------------ context menu
        ["Menu.Open"] = "Open",
        ["Menu.Reveal"] = "Show in file manager",
        ["Menu.Terminal"] = "Open terminal here",
        ["Menu.CopyPath"] = "Copy path",
        ["Menu.ZoomInto"] = "Zoom into",
        ["Menu.Rescan"] = "Rescan this folder",
        ["Menu.Trash"] = "Move to trash",
        ["Menu.DeletePermanently"] = "Delete permanently…",

        // --------------------------------------------------------------- options
        ["Options.Title"] = "Options",
        ["Options.Units"] = "Switch units (KiB / KB)",
        ["Options.SizeOnDisk"] = "Switch size / size on disk",
        ["Options.Theme"] = "Switch light / dark theme",
        ["Options.Exclusions"] = "Exclusion rules…",
        ["Options.Keyboard"] = "KEYBOARD",
        ["Options.Shortcuts"] = "Enter — zoom into folder\nBackspace — zoom out\nArrows — walk the chart\nCtrl+F — focus filter\nF5 — rescan selection\nDelete — move to trash\nShift+Delete — delete permanently",

        // --------------------------------------------------------------- confirm
        ["Confirm.TrashTitle"] = "Move to trash?",
        ["Confirm.DeleteTitle"] = "Delete permanently?",
        ["Confirm.TrashBody"] = "{0} will be moved to the trash.\n\n{1}",
        ["Confirm.DeleteBody"] = "{0} will be erased immediately. This cannot be undone.\n\n{1}",
        ["Confirm.AndFiles"] = "{0} and its {1} files",

        // ------------------------------------------------------------- duplicates
        ["Dup.Title"] = "Find what you have twice",
        ["Dup.Subtitle"] = "DirStat compares contents, not names. Two files match only when every byte does, and two folders match only when their entire trees do.",
        ["Dup.MinSize"] = "IGNORE FILES SMALLER THAN",
        ["Dup.MinSizeHint"] = "Small files duplicate constantly and reclaim almost nothing.",
        ["Dup.Verify"] = "Verify byte for byte after matching",
        ["Dup.VerifyHint"] = "Reads every confirmed duplicate a second time. The 128-bit content hash already makes a false match vanishingly unlikely.",
        ["Dup.Find"] = "Find duplicates",
        ["Dup.SearchAgain"] = "Search again",
        ["Dup.ExpandAll"] = "Expand all",
        ["Dup.Collapse"] = "Collapse",
        ["Dup.EmptyTitle"] = "Nothing duplicated here",
        ["Dup.EmptyFiles"] = "No duplicate files above the minimum size.",
        ["Dup.EmptyFolders"] = "No duplicate folders. Folders match only when their entire contents do.",
        ["Dup.Keep"] = "Keep",
        ["Dup.Oldest"] = "Oldest",
        ["Dup.Newest"] = "Newest",
        ["Dup.ShortestPath"] = "Shortest path",
        ["Dup.KeepOldestTip"] = "Tick every copy except the oldest in each group",
        ["Dup.KeepNewestTip"] = "Tick every copy except the newest in each group",
        ["Dup.KeepShortestTip"] = "Tick every copy except the one nearest the root",
        ["Dup.MoveToTrash"] = "Move selected to trash",
        ["Dup.NothingSelected"] = "Nothing selected",
        ["Dup.Selected"] = "{0} selected  ·  {1} to recover",
        ["Dup.Copies"] = "{0} copies",
        ["Dup.Recoverable"] = "recoverable",
        ["Dup.Summary"] = "{0} recoverable  ·  {1} groups  ·  {2} read in {3}",
        ["Dup.NoneFound"] = "No duplicates found  ·  searched in {0}",
        ["Dup.Cancelled"] = "Search cancelled — showing partial results.",
        ["Dup.StaleTotals"] = "Totals are out of date after removing copies — search again to refresh.",
        ["Dup.ConfirmTitle"] = "Move duplicates to trash?",
        ["Dup.ConfirmBody"] = "{0} will be moved to the trash, recovering {1}.\n\nOne copy of every group is always kept.",
        ["Dup.FilesTab"] = "Files  ({0})",
        ["Dup.FoldersTab"] = "Folders  ({0})",
        ["Dup.NFiles"] = "{0} files",
        ["Dup.Candidates"] = "{0} candidates",
        ["Dup.BytesRead"] = "{0} read",
        ["Dup.Moved"] = "Moved {0} to trash, recovering {1}.",
        ["Dup.MovedPartial"] = "Moved {0}; {1} could not be removed.",
        ["Dup.Phase.Grouping"] = "Grouping by size",
        ["Dup.Phase.Screening"] = "Screening candidates",
        ["Dup.Phase.Hashing"] = "Comparing contents",
        ["Dup.Phase.Folders"] = "Matching folders",
        ["Dup.Phase.Verifying"] = "Verifying byte for byte",
        ["Dup.Phase.Finishing"] = "Finishing",
        ["Dup.Item"] = "item",
        ["Dup.Items"] = "items",
        ["Dup.Folder"] = "folder",
        ["Dup.FoldersPlural"] = "folders",

        // -------------------------------------------------------------- insights
        ["Insights.Title"] = "Worth a second look",
        ["Insights.Subtitle"] = "Everything here comes from the scan you already ran. Nothing is deleted without you saying so.",
        ["Insights.Analyse"] = "Analyse",
        ["Insights.Empty"] = "Nothing stood out. Your disk looks tidy.",
        ["Insights.Reclaimable"] = "{0} across {1} groups",
        ["Insights.StaleFile"] = "Old files",
        ["Insights.StaleFileHelp"] = "Large files untouched for years. Old does not mean unwanted — check before removing.",
        ["Insights.EmptyFolder"] = "Empty folders",
        ["Insights.EmptyFolderHelp"] = "Folders with nothing inside them at any depth. They cost no space, only clutter.",
        ["Insights.ZeroByteFile"] = "Zero-byte files",
        ["Insights.ZeroByteFileHelp"] = "Files with no content. Sometimes placeholders that something still expects to find.",
        ["Insights.Junk"] = "Rebuildable data",
        ["Insights.Items"] = "{0} items",
        ["Insights.Warning"] = "DirStat identifies these by name and shape, not by asking the program that made them. Read what each category is before removing anything, and never act on this while a build or install is running.",
        ["Insights.WarningTitle"] = "Read this first",
        ["Confidence.Rebuildable"] = "Rebuilt automatically",
        ["Confidence.RebuildableHelp"] = "Regenerated on next use. Removing costs time, never data.",
        ["Confidence.Likely"] = "Usually disposable",
        ["Confidence.LikelyHelp"] = "Almost certainly safe, but worth a glance first.",
        ["Confidence.Review"] = "Check carefully",
        ["Confidence.ReviewHelp"] = "Often large and often unwanted, but may be there on purpose.",
        ["Junk.NodeModules"] = "Node.js packages (node_modules)",
        ["Junk.BuildOutput"] = "Build output",
        ["Junk.PackageCache"] = "Package manager caches",
        ["Junk.PythonCache"] = "Python caches",
        ["Junk.ToolCache"] = "Tool caches",
        ["Junk.Temp"] = "Temporary files",
        ["Junk.Logs"] = "Log files",
        ["Junk.Backups"] = "Backup copies",
        ["Junk.Installers"] = "Installers and disc images",

        // ------------------------------------------------------------- snapshots
        ["Snap.Title"] = "What changed?",
        ["Snap.Subtitle"] = "Compare this scan against one you stored earlier to see exactly where the space went.",
        ["Snap.Save"] = "Save snapshot",
        ["Snap.Saved"] = "Snapshot saved",
        ["Snap.NoSnapshots"] = "No snapshots yet. Save one now, then compare against it after a few days.",
        ["Snap.Compare"] = "Compare",
        ["Snap.Taken"] = "Taken {0}",
        ["Snap.Before"] = "BEFORE",
        ["Snap.After"] = "AFTER",
        ["Snap.Change"] = "CHANGE",
        ["Snap.Grew"] = "Grew",
        ["Snap.Shrank"] = "Shrank",
        ["Snap.Added"] = "Added",
        ["Snap.Removed"] = "Removed",
        ["Snap.NoChanges"] = "Nothing changed by more than a megabyte.",
        ["Snap.Changes"] = "CHANGES",

        // ------------------------------------------------------------ exclusions
        ["Excl.Title"] = "Exclusion rules",
        ["Excl.Subtitle"] = "Folder names skipped wherever they appear. Useful for caches you never want counted.",
        ["Excl.Placeholder"] = "Folder name, for example node_modules",
        ["Excl.Empty"] = "No exclusions. Every folder is scanned.",
        ["Excl.Suggestions"] = "COMMON",
        ["Insights.Item"] = "{0} item",

        // --------------------------------------------------------------- families
        ["Family.Video"] = "Video",
        ["Family.Image"] = "Images",
        ["Family.Audio"] = "Audio",
        ["Family.Archive"] = "Archives",
        ["Family.Document"] = "Documents",
        ["Family.Code"] = "Code",
        ["Family.Web"] = "Web",
        ["Family.Executable"] = "Programs",
        ["Family.Database"] = "Databases",
        ["Family.Font"] = "Fonts",
        ["Family.DiskImage"] = "Disc images",
        ["Family.System"] = "System",
        ["Family.Other"] = "Other",

        // -------------------------------------------------------------- tooltips
        ["Tooltip.Size"] = "Size",
        ["Tooltip.OnDisk"] = "On disk",
        ["Tooltip.Files"] = "Files",
        ["Tooltip.Directories"] = "Directories",
        ["Tooltip.OfParent"] = "Of parent",
        ["Tooltip.Modified"] = "Modified",
        ["Tooltip.AccessDenied"] = "Access denied — contents are not included.",
        ["Tooltip.Link"] = "Link — not followed, so its target is counted only where it really lives.",
        ["Tooltip.HardLink"] = "Hard link — the bytes are counted at the first path found.",
        ["Tooltip.UnknownSpace"] = "Space the volume reports as used but the scan could not see.",
        ["Tooltip.FreeSpace"] = "Unallocated space on this volume.",
        ["Tooltip.Denied"] = "Some folders require elevated rights. Their contents show as unknown space.",

        // --------------------------------------------------------------- status
        ["Status.PathCopied"] = "Path copied to clipboard.",
        ["Status.ScanFailed"] = "Scan failed: {0}",
        ["Status.ScanCancelled"] = "Scan cancelled — showing partial results.",
        ["Status.Refreshed"] = "Refreshed {0}.",
        ["Status.RefreshFailed"] = "Refresh failed: {0}",
        ["Status.Exported"] = "Exported to {0}",
        ["Status.ExportFailed"] = "Export failed: {0}",
        ["Status.ImageSaved"] = "Chart saved to {0}",
        ["Status.Deleted"] = "Deleted {0}.",
        ["Status.Trashed"] = "Moved {0} to trash.",
        ["Status.PickerFailed"] = "Could not open the folder picker: {0}",
        ["Status.SaveDialogFailed"] = "Could not open the save dialog: {0}",
        ["Status.DeniedFolders"] = "{0} folders could not be read",
        ["Status.RecoveredDuplicates"] = "Recovered space from {0} duplicates.",
        ["Status.SnapshotSaved"] = "Snapshot saved to {0}",
        ["Status.SnapshotFailed"] = "Could not save the snapshot: {0}",

        // -------------------------------------------------------------- summary
        ["Summary.Scan"] = "{0}  ·  {1} files  ·  {2} folders  ·  scanned in {3}",
        ["Summary.OfParent"] = "{0} of parent",
        ["Summary.NFiles"] = "{0} files",
        ["Summary.NFolders"] = "{0} folders",
    };
}
