namespace DirStat.App.Localization;

public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>
    {
        // ---------------------------------------------------------------- common
        ["Common.Cancel"] = "Cancelar",
        ["Common.Continue"] = "Continuar",
        ["Common.Back"] = "Atrás",
        ["Common.Clear"] = "Limpiar",
        ["Common.Apply"] = "Aplicar",
        ["Common.Add"] = "Añadir",
        ["Common.Remove"] = "Quitar",
        ["Common.Files"] = "Archivos",
        ["Common.Folders"] = "Carpetas",
        ["Common.Name"] = "Nombre",
        ["Common.Size"] = "Tamaño",
        ["Common.Share"] = "PROPORCIÓN",
        ["Common.Items"] = "Elementos",
        ["Common.Modified"] = "Modificado",
        ["Common.Dash"] = "—",

        // ---------------------------------------------------------------- window
        ["Window.Theme"] = "Cambiar tema",
        ["Window.Language"] = "Idioma",
        ["Window.Minimise"] = "Minimizar",
        ["Window.Maximise"] = "Maximizar",
        ["Window.Close"] = "Cerrar",

        // --------------------------------------------------------------- volumes
        ["Volumes.Title"] = "¿Adónde se fue tu espacio?",
        ["Volumes.Subtitle"] = "Elige una unidad o una carpeta. DirStat cartografía cada byte y muestra qué merece la pena borrar.",
        ["Volumes.Drives"] = "UNIDADES",
        ["Volumes.FreeOf"] = "libres de",
        ["Volumes.OrFolder"] = "O UNA CARPETA CONCRETA",
        ["Volumes.ChooseFolders"] = "Elegir carpetas…",
        ["Volumes.ChooseHint"] = "Puedes seleccionar varias — se analizan juntas.",
        ["Volumes.Recent"] = "RECIENTES",
        ["Volumes.Compare"] = "Comparar con una instantánea",

        // ------------------------------------------------------------------ scan
        ["Scan.Title"] = "Analizando",
        ["Scan.Files"] = "ARCHIVOS",
        ["Scan.Folders"] = "CARPETAS",
        ["Scan.TotalSize"] = "TAMAÑO TOTAL",
        ["Scan.Elapsed"] = "TIEMPO",
        ["Scan.Throughput"] = "RENDIMIENTO",
        ["Scan.CurrentFolder"] = "CARPETA ACTUAL",
        ["Scan.Cancel"] = "Cancelar análisis",
        ["Scan.CancelHint"] = "Al cancelar se sigue mostrando todo lo encontrado hasta ahora.",
        ["Scan.FilesPerSecond"] = "{0} archivos/s",
        ["Scan.Locations"] = "{0} ubicaciones",

        // --------------------------------------------------------------- results
        ["Results.Drives"] = "Unidades",
        ["Results.BackToDrives"] = "Volver a las unidades",
        ["Results.FilterWatermark"] = "Filtro: prueba  *.mp4  >100mb  after:2025-01-01",
        ["Results.FilterTooltip"] = "Los términos se combinan: el texto busca en los nombres, *.ext filtra por tipo,\n>100mb y <1gb limitan el tamaño, after: y before: limitan las fechas.",
        ["Results.Duplicates"] = "Duplicados",
        ["Results.DuplicatesTooltip"] = "Encontrar archivos y carpetas de los que tienes más de una copia",
        ["Results.Insights"] = "Hallazgos",
        ["Results.InsightsTooltip"] = "Archivos antiguos, carpetas vacías y cachés reconstruibles",
        ["Results.ZoomOut"] = "Subir un nivel",
        ["Results.Rescan"] = "Volver a analizar la carpeta seleccionada (F5)",
        ["Results.Options"] = "Opciones",
        ["Results.Folders"] = "CARPETAS",
        ["Results.Treemap"] = "TREEMAP",
        ["Results.Sunburst"] = "DIAGRAMA RADIAL",
        ["Results.ChartHint"] = "clic para seleccionar  ·  doble clic para ampliar  ·  flechas para recorrer",
        ["Results.FileTypes"] = "TIPOS DE ARCHIVO",
        ["Results.ClickToIsolate"] = "clic para aislar",
        ["Results.ExportCsv"] = "Exportar CSV",
        ["Results.ExportJson"] = "JSON",
        ["Results.ExportImage"] = "Guardar imagen",
        ["Results.ExportImageTooltip"] = "Guardar la vista actual como PNG",
        ["Results.ToggleChart"] = "Alternar entre treemap y diagrama radial",
        ["Results.SaveSnapshot"] = "Guardar instantánea",
        ["Results.SaveSnapshotTooltip"] = "Guardar este análisis para comparar más adelante",
        ["Results.NoExtension"] = "(sin extensión)",
        ["Results.FreeSpace"] = "Espacio libre",
        ["Results.UnknownSpace"] = "Desconocido",

        // ------------------------------------------------------------ context menu
        ["Menu.Open"] = "Abrir",
        ["Menu.Reveal"] = "Mostrar en el explorador",
        ["Menu.Terminal"] = "Abrir terminal aquí",
        ["Menu.CopyPath"] = "Copiar ruta",
        ["Menu.ZoomInto"] = "Ampliar dentro",
        ["Menu.Rescan"] = "Volver a analizar esta carpeta",
        ["Menu.Trash"] = "Mover a la papelera",
        ["Menu.DeletePermanently"] = "Eliminar permanentemente…",

        // --------------------------------------------------------------- options
        ["Options.Title"] = "Opciones",
        ["Options.Units"] = "Cambiar unidades (KiB / KB)",
        ["Options.SizeOnDisk"] = "Tamaño / espacio ocupado",
        ["Options.Theme"] = "Tema claro / oscuro",
        ["Options.Exclusions"] = "Reglas de exclusión…",
        ["Options.Keyboard"] = "TECLADO",
        ["Options.Shortcuts"] = "Intro — ampliar dentro de la carpeta\nRetroceso — reducir\nFlechas — recorrer la vista\nCtrl+F — activar el filtro\nF5 — volver a analizar la selección\nSupr — mover a la papelera\nMayús+Supr — eliminar permanentemente",

        // --------------------------------------------------------------- confirm
        ["Confirm.TrashTitle"] = "¿Mover a la papelera?",
        ["Confirm.DeleteTitle"] = "¿Eliminar permanentemente?",
        ["Confirm.TrashBody"] = "{0} se moverá a la papelera.\n\n{1}",
        ["Confirm.DeleteBody"] = "{0} se borrará de inmediato. Esto no se puede deshacer.\n\n{1}",
        ["Confirm.AndFiles"] = "{0} y sus {1} archivos",

        // ------------------------------------------------------------- duplicates
        ["Dup.Title"] = "Encuentra lo que tienes dos veces",
        ["Dup.Subtitle"] = "DirStat compara contenidos, no nombres. Dos archivos coinciden solo si cada byte coincide, y dos carpetas solo si coinciden sus árboles completos.",
        ["Dup.MinSize"] = "IGNORAR ARCHIVOS MENORES DE",
        ["Dup.MinSizeHint"] = "Los archivos pequeños se duplican constantemente y apenas liberan espacio.",
        ["Dup.Verify"] = "Verificar byte a byte tras la coincidencia",
        ["Dup.VerifyHint"] = "Lee cada duplicado confirmado una segunda vez. El hash de contenido de 128 bits ya hace que una falsa coincidencia sea sumamente improbable.",
        ["Dup.Find"] = "Buscar duplicados",
        ["Dup.SearchAgain"] = "Buscar de nuevo",
        ["Dup.ExpandAll"] = "Expandir todo",
        ["Dup.Collapse"] = "Contraer",
        ["Dup.EmptyTitle"] = "Aquí no hay nada duplicado",
        ["Dup.EmptyFiles"] = "No hay archivos duplicados por encima del tamaño mínimo.",
        ["Dup.EmptyFolders"] = "No hay carpetas duplicadas. Las carpetas coinciden solo si coincide todo su contenido.",
        ["Dup.Keep"] = "Conservar",
        ["Dup.Oldest"] = "La más antigua",
        ["Dup.Newest"] = "La más reciente",
        ["Dup.ShortestPath"] = "Ruta más corta",
        ["Dup.KeepOldestTip"] = "Marcar todas las copias salvo la más antigua de cada grupo",
        ["Dup.KeepNewestTip"] = "Marcar todas las copias salvo la más reciente de cada grupo",
        ["Dup.KeepShortestTip"] = "Marcar todas las copias salvo la más cercana a la raíz",
        ["Dup.MoveToTrash"] = "Mover lo seleccionado a la papelera",
        ["Dup.NothingSelected"] = "Nada seleccionado",
        ["Dup.Selected"] = "{0} seleccionados  ·  {1} por recuperar",
        ["Dup.Copies"] = "{0} copias",
        ["Dup.Recoverable"] = "recuperable",
        ["Dup.Summary"] = "{0} recuperables  ·  {1} grupos  ·  {2} leídos en {3}",
        ["Dup.NoneFound"] = "No se encontraron duplicados  ·  búsqueda en {0}",
        ["Dup.Cancelled"] = "Búsqueda cancelada — se muestran resultados parciales.",
        ["Dup.StaleTotals"] = "Los totales están desactualizados tras eliminar copias — busca de nuevo.",
        ["Dup.ConfirmTitle"] = "¿Mover los duplicados a la papelera?",
        ["Dup.ConfirmBody"] = "{0} se moverán a la papelera y liberarán {1}.\n\nSiempre se conserva una copia de cada grupo.",
        ["Dup.FilesTab"] = "Archivos  ({0})",
        ["Dup.FoldersTab"] = "Carpetas  ({0})",
        ["Dup.NFiles"] = "{0} archivos",
        ["Dup.Candidates"] = "{0} candidatos",
        ["Dup.BytesRead"] = "{0} leídos",
        ["Dup.Moved"] = "{0} movidos a la papelera, {1} liberados.",
        ["Dup.MovedPartial"] = "{0} movidos; {1} no se pudieron eliminar.",
        ["Dup.Phase.Grouping"] = "Agrupando por tamaño",
        ["Dup.Phase.Screening"] = "Preseleccionando candidatos",
        ["Dup.Phase.Hashing"] = "Comparando contenidos",
        ["Dup.Phase.Folders"] = "Emparejando carpetas",
        ["Dup.Phase.Verifying"] = "Verificando byte a byte",
        ["Dup.Phase.Finishing"] = "Finalizando",
        ["Dup.Item"] = "elemento",
        ["Dup.Items"] = "elementos",
        ["Dup.Folder"] = "carpeta",
        ["Dup.FoldersPlural"] = "carpetas",

        // -------------------------------------------------------------- insights
        ["Insights.Title"] = "Merece una segunda mirada",
        ["Insights.Subtitle"] = "Todo esto sale del análisis que ya hiciste. No se borra nada sin que tú lo digas.",
        ["Insights.Analyse"] = "Analizar",
        ["Insights.Empty"] = "No destacó nada. Tu disco está ordenado.",
        ["Insights.Reclaimable"] = "{0} en {1} grupos",
        ["Insights.StaleFile"] = "Archivos antiguos",
        ["Insights.StaleFileHelp"] = "Archivos grandes sin tocar durante años. Antiguo no significa prescindible: compruébalo antes de borrar.",
        ["Insights.EmptyFolder"] = "Carpetas vacías",
        ["Insights.EmptyFolderHelp"] = "Carpetas sin nada dentro a ninguna profundidad. No ocupan espacio, solo estorban.",
        ["Insights.ZeroByteFile"] = "Archivos de cero bytes",
        ["Insights.ZeroByteFileHelp"] = "Archivos sin contenido. A veces son marcadores que algún programa aún espera encontrar.",
        ["Insights.Junk"] = "Datos reconstruibles",
        ["Insights.Items"] = "{0} elementos",
        ["Insights.Warning"] = "DirStat los identifica por su nombre y su forma, no preguntando al programa que los creó. Lee qué es cada categoría antes de borrar nada, y nunca lo hagas mientras se ejecuta una compilación o una instalación.",
        ["Insights.WarningTitle"] = "Léelo primero",
        ["Confidence.Rebuildable"] = "Se reconstruye solo",
        ["Confidence.RebuildableHelp"] = "Se regenera al usarlo de nuevo. Borrarlo cuesta tiempo, nunca datos.",
        ["Confidence.Likely"] = "Normalmente prescindible",
        ["Confidence.LikelyHelp"] = "Casi con seguridad seguro, pero conviene echar un vistazo.",
        ["Confidence.Review"] = "Revísalo con cuidado",
        ["Confidence.ReviewHelp"] = "A menudo grande y a menudo no deseado, pero puede estar ahí a propósito.",
        ["Junk.NodeModules"] = "Paquetes de Node.js (node_modules)",
        ["Junk.BuildOutput"] = "Resultados de compilación",
        ["Junk.PackageCache"] = "Cachés de gestores de paquetes",
        ["Junk.PythonCache"] = "Cachés de Python",
        ["Junk.ToolCache"] = "Cachés de herramientas",
        ["Junk.Temp"] = "Archivos temporales",
        ["Junk.Logs"] = "Archivos de registro",
        ["Junk.Backups"] = "Copias de seguridad",
        ["Junk.Installers"] = "Instaladores e imágenes de disco",

        // ------------------------------------------------------------- snapshots
        ["Snap.Title"] = "¿Qué ha cambiado?",
        ["Snap.Subtitle"] = "Compara este análisis con otro guardado antes para ver exactamente adónde se fue el espacio.",
        ["Snap.Save"] = "Guardar instantánea",
        ["Snap.Saved"] = "Instantánea guardada",
        ["Snap.NoSnapshots"] = "Todavía no hay instantáneas. Guarda una ahora y compara dentro de unos días.",
        ["Snap.Compare"] = "Comparar",
        ["Snap.Taken"] = "Tomada el {0}",
        ["Snap.Before"] = "ANTES",
        ["Snap.After"] = "DESPUÉS",
        ["Snap.Change"] = "CAMBIO",
        ["Snap.Grew"] = "Creció",
        ["Snap.Shrank"] = "Menguó",
        ["Snap.Added"] = "Añadido",
        ["Snap.Removed"] = "Eliminado",
        ["Snap.NoChanges"] = "Nada cambió más de un megabyte.",
        ["Snap.Changes"] = "CAMBIOS",

        // ------------------------------------------------------------ exclusions
        ["Excl.Title"] = "Reglas de exclusión",
        ["Excl.Subtitle"] = "Nombres de carpeta que se omiten en cualquier lugar. Útil para cachés que nunca quieres contar.",
        ["Excl.Placeholder"] = "Nombre de carpeta, por ejemplo node_modules",
        ["Excl.Empty"] = "Sin exclusiones. Se analizan todas las carpetas.",
        ["Excl.Suggestions"] = "HABITUALES",

        // -------------------------------------------------------------- tooltips
        ["Tooltip.Size"] = "Tamaño",
        ["Tooltip.OnDisk"] = "En disco",
        ["Tooltip.Files"] = "Archivos",
        ["Tooltip.Directories"] = "Carpetas",
        ["Tooltip.OfParent"] = "Del contenedor",
        ["Tooltip.Modified"] = "Modificado",
        ["Tooltip.AccessDenied"] = "Acceso denegado — el contenido no está incluido.",
        ["Tooltip.Link"] = "Enlace — no se sigue, su destino se cuenta solo donde reside realmente.",
        ["Tooltip.HardLink"] = "Enlace duro — los bytes se cuentan en la primera ruta encontrada.",
        ["Tooltip.UnknownSpace"] = "Espacio que el volumen declara ocupado pero que el análisis no pudo ver.",
        ["Tooltip.FreeSpace"] = "Espacio no asignado en este volumen.",
        ["Tooltip.Denied"] = "Algunas carpetas requieren permisos elevados. Su contenido aparece como espacio desconocido.",

        // --------------------------------------------------------------- status
        ["Status.PathCopied"] = "Ruta copiada al portapapeles.",
        ["Status.ScanFailed"] = "Error en el análisis: {0}",
        ["Status.ScanCancelled"] = "Análisis cancelado — se muestran resultados parciales.",
        ["Status.Refreshed"] = "{0} vuelto a analizar.",
        ["Status.RefreshFailed"] = "Error al volver a analizar: {0}",
        ["Status.Exported"] = "Exportado a {0}",
        ["Status.ExportFailed"] = "Error al exportar: {0}",
        ["Status.ImageSaved"] = "Vista guardada en {0}",
        ["Status.Deleted"] = "{0} eliminado.",
        ["Status.Trashed"] = "{0} movido a la papelera.",
        ["Status.PickerFailed"] = "No se pudo abrir el selector de carpetas: {0}",
        ["Status.SaveDialogFailed"] = "No se pudo abrir el diálogo de guardado: {0}",
        ["Status.DeniedFolders"] = "No se pudieron leer {0} carpetas",
        ["Status.RecoveredDuplicates"] = "Espacio recuperado de {0} duplicados.",
        ["Status.SnapshotSaved"] = "Instantánea guardada en {0}",
        ["Status.SnapshotFailed"] = "No se pudo guardar la instantánea: {0}",

        // -------------------------------------------------------------- summary
        ["Summary.Scan"] = "{0}  ·  {1} archivos  ·  {2} carpetas  ·  analizado en {3}",
        ["Summary.OfParent"] = "{0} del contenedor",
        ["Summary.NFiles"] = "{0} archivos",
        ["Summary.NFolders"] = "{0} carpetas",
    };
}
