namespace DirStat.App.Localization;

public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> French = new Dictionary<string, string>
    {
        // ---------------------------------------------------------------- common
        ["Common.Cancel"] = "Annuler",
        ["Common.Continue"] = "Continuer",
        ["Common.Back"] = "Retour",
        ["Common.Clear"] = "Effacer",
        ["Common.Apply"] = "Appliquer",
        ["Common.Add"] = "Ajouter",
        ["Common.Remove"] = "Supprimer",
        ["Common.Files"] = "Fichiers",
        ["Common.Folders"] = "Dossiers",
        ["Common.Name"] = "Nom",
        ["Common.Size"] = "Taille",
        ["Common.Share"] = "PART",
        ["Common.Items"] = "Éléments",
        ["Common.Modified"] = "Modifié",
        ["Common.Dash"] = "—",

        // ---------------------------------------------------------------- window
        ["Window.Theme"] = "Changer de thème",
        ["Window.Language"] = "Langue",
        ["Window.Minimise"] = "Réduire",
        ["Window.Maximise"] = "Agrandir",
        ["Window.Close"] = "Fermer",
        ["Window.About"] = "À propos de DirStat",

        // ----------------------------------------------------------------- about
        ["About.Title"] = "DirStat",
        ["About.Tagline"] = "Découvrez où est passé votre espace disque, sur les trois plateformes.",
        ["About.MadeBy"] = "Créé par",
        ["About.Version"] = "Version",
        ["About.Licence"] = "Licence",
        ["About.LicenceValue"] = "MIT — libre d'utilisation, de modification et de partage.",
        ["About.BuiltWith"] = "Développé avec",
        ["About.System"] = "Système",
        ["About.Thanks"] = "Merci à WinDirStat, QDirStat et SpaceSniffer, qui ont montré ce qu'un tel outil doit faire.",
        ["About.Copy"] = "Copier les détails",
        ["About.Copied"] = "Copié",
        ["About.Close"] = "Fermer",

        // --------------------------------------------------------------- volumes
        ["Volumes.Title"] = "Où est passé votre espace ?",
        ["Volumes.Subtitle"] = "Choisissez un disque ou un dossier. DirStat cartographie chaque octet et montre ce qui mérite d'être supprimé.",
        ["Volumes.Drives"] = "DISQUES",
        ["Volumes.FreeOf"] = "libres sur",
        ["Volumes.OrFolder"] = "OU UN DOSSIER PRÉCIS",
        ["Volumes.ChooseFolders"] = "Choisir des dossiers…",
        ["Volumes.ChooseHint"] = "Vous pouvez en sélectionner plusieurs — ils sont analysés ensemble.",
        ["Volumes.Recent"] = "RÉCENTS",
        ["Volumes.Compare"] = "Comparer à un instantané",

        // ------------------------------------------------------------------ scan
        ["Scan.Title"] = "Analyse en cours",
        ["Scan.Files"] = "FICHIERS",
        ["Scan.Folders"] = "DOSSIERS",
        ["Scan.TotalSize"] = "TAILLE TOTALE",
        ["Scan.Elapsed"] = "DURÉE",
        ["Scan.Throughput"] = "DÉBIT",
        ["Scan.CurrentFolder"] = "DOSSIER EN COURS",
        ["Scan.Cancel"] = "Annuler l'analyse",
        ["Scan.CancelHint"] = "Après annulation, tout ce qui a été trouvé reste affiché.",
        ["Scan.FilesPerSecond"] = "{0} fichiers/s",
        ["Scan.Locations"] = "{0} emplacements",

        // --------------------------------------------------------------- results
        ["Results.Drives"] = "Disques",
        ["Results.BackToDrives"] = "Retour aux disques",
        ["Results.FilterWatermark"] = "Filtre : essayez  *.mp4  >100mb  after:2025-01-01",
        ["Results.FilterTooltip"] = "Les termes se combinent : le texte cherche dans les noms, *.ext cible un type,\n>100mb et <1gb bornent la taille, after: et before: bornent les dates.",
        ["Results.Duplicates"] = "Doublons",
        ["Results.DuplicatesTooltip"] = "Trouver les fichiers et dossiers présents en plusieurs exemplaires",
        ["Results.Insights"] = "Analyses",
        ["Results.InsightsTooltip"] = "Fichiers anciens, dossiers vides et caches reconstructibles",
        ["Results.ZoomOut"] = "Remonter d'un niveau",
        ["Results.Rescan"] = "Réanalyser le dossier sélectionné (F5)",
        ["Results.Options"] = "Options",
        ["Results.Folders"] = "DOSSIERS",
        ["Results.Treemap"] = "TREEMAP",
        ["Results.Sunburst"] = "DIAGRAMME RADIAL",
        ["Results.ChartHint"] = "cliquer pour sélectionner  ·  double-clic pour zoomer  ·  flèches pour parcourir",
        ["Results.FileTypes"] = "TYPES DE FICHIERS",
        ["Results.ClickToIsolate"] = "cliquer pour isoler",
        ["Results.ExportCsv"] = "Exporter en CSV",
        ["Results.ExportJson"] = "JSON",
        ["Results.ExportImage"] = "Enregistrer l'image",
        ["Results.ExportImageTooltip"] = "Enregistrer la vue actuelle au format PNG",
        ["Results.ToggleChart"] = "Basculer entre treemap et diagramme radial",
        ["Results.SaveSnapshot"] = "Enregistrer un instantané",
        ["Results.SaveSnapshotTooltip"] = "Conserver cette analyse pour la comparer plus tard",
        ["Results.NoExtension"] = "(sans extension)",
        ["Results.FreeSpace"] = "Espace libre",
        ["Results.UnknownSpace"] = "Inconnu",

        // ------------------------------------------------------------ context menu
        ["Menu.Open"] = "Ouvrir",
        ["Menu.Reveal"] = "Afficher dans le gestionnaire de fichiers",
        ["Menu.Terminal"] = "Ouvrir un terminal ici",
        ["Menu.CopyPath"] = "Copier le chemin",
        ["Menu.ZoomInto"] = "Zoomer dedans",
        ["Menu.Rescan"] = "Réanalyser ce dossier",
        ["Menu.Trash"] = "Mettre à la corbeille",
        ["Menu.DeletePermanently"] = "Supprimer définitivement…",

        // --------------------------------------------------------------- options
        ["Options.Title"] = "Options",
        ["Options.Units"] = "Changer d'unités (Kio / Ko)",
        ["Options.SizeOnDisk"] = "Taille / espace occupé",
        ["Options.Theme"] = "Thème clair / sombre",
        ["Options.Exclusions"] = "Règles d'exclusion…",
        ["Options.Keyboard"] = "CLAVIER",
        ["Options.Shortcuts"] = "Entrée — zoomer dans le dossier\nRetour arrière — dézoomer\nFlèches — parcourir la vue\nCtrl+F — activer le filtre\nF5 — réanalyser la sélection\nSuppr — mettre à la corbeille\nMaj+Suppr — supprimer définitivement",

        // --------------------------------------------------------------- confirm
        ["Confirm.TrashTitle"] = "Mettre à la corbeille ?",
        ["Confirm.DeleteTitle"] = "Supprimer définitivement ?",
        ["Confirm.TrashBody"] = "{0} sera mis à la corbeille.\n\n{1}",
        ["Confirm.DeleteBody"] = "{0} sera effacé immédiatement. Cette action est irréversible.\n\n{1}",
        ["Confirm.AndFiles"] = "{0} et ses {1} fichiers",

        // ------------------------------------------------------------- duplicates
        ["Dup.Title"] = "Trouver ce que vous avez en double",
        ["Dup.Subtitle"] = "DirStat compare les contenus, pas les noms. Deux fichiers correspondent uniquement si chaque octet correspond, et deux dossiers uniquement si toute leur arborescence correspond.",
        ["Dup.MinSize"] = "IGNORER LES FICHIERS PLUS PETITS QUE",
        ["Dup.MinSizeHint"] = "Les petits fichiers se dupliquent sans cesse et ne libèrent presque rien.",
        ["Dup.Verify"] = "Vérifier octet par octet après correspondance",
        ["Dup.VerifyHint"] = "Relit chaque doublon confirmé une seconde fois. L'empreinte de contenu sur 128 bits rend déjà une fausse correspondance extrêmement improbable.",
        ["Dup.Find"] = "Rechercher les doublons",
        ["Dup.SearchAgain"] = "Rechercher à nouveau",
        ["Dup.ExpandAll"] = "Tout déplier",
        ["Dup.Collapse"] = "Replier",
        ["Dup.EmptyTitle"] = "Rien n'est en double ici",
        ["Dup.EmptyFiles"] = "Aucun fichier en double au-dessus de la taille minimale.",
        ["Dup.EmptyFolders"] = "Aucun dossier en double. Les dossiers ne correspondent que si tout leur contenu correspond.",
        ["Dup.Keep"] = "Conserver",
        ["Dup.Oldest"] = "Le plus ancien",
        ["Dup.Newest"] = "Le plus récent",
        ["Dup.ShortestPath"] = "Chemin le plus court",
        ["Dup.KeepOldestTip"] = "Cocher toutes les copies sauf la plus ancienne de chaque groupe",
        ["Dup.KeepNewestTip"] = "Cocher toutes les copies sauf la plus récente de chaque groupe",
        ["Dup.KeepShortestTip"] = "Cocher toutes les copies sauf celle la plus proche de la racine",
        ["Dup.MoveToTrash"] = "Mettre la sélection à la corbeille",
        ["Dup.NothingSelected"] = "Rien de sélectionné",
        ["Dup.Selected"] = "{0} sélectionnés  ·  {1} à récupérer",
        ["Dup.Copies"] = "{0} copies",
        ["Dup.Recoverable"] = "récupérable",
        ["Dup.Summary"] = "{0} récupérables  ·  {1} groupes  ·  {2} lus en {3}",
        ["Dup.NoneFound"] = "Aucun doublon trouvé  ·  recherche en {0}",
        ["Dup.Cancelled"] = "Recherche annulée — résultats partiels affichés.",
        ["Dup.StaleTotals"] = "Les totaux ne sont plus à jour après suppression — relancez la recherche.",
        ["Dup.ConfirmTitle"] = "Mettre les doublons à la corbeille ?",
        ["Dup.ConfirmBody"] = "{0} seront mis à la corbeille et libéreront {1}.\n\nUne copie de chaque groupe est toujours conservée.",
        ["Dup.FilesTab"] = "Fichiers  ({0})",
        ["Dup.FoldersTab"] = "Dossiers  ({0})",
        ["Dup.NFiles"] = "{0} fichiers",
        ["Dup.Candidates"] = "{0} candidats",
        ["Dup.BytesRead"] = "{0} lus",
        ["Dup.Moved"] = "{0} mis à la corbeille, {1} libérés.",
        ["Dup.MovedPartial"] = "{0} déplacés ; {1} n'ont pas pu être supprimés.",
        ["Dup.Phase.Grouping"] = "Regroupement par taille",
        ["Dup.Phase.Screening"] = "Présélection des candidats",
        ["Dup.Phase.Hashing"] = "Comparaison des contenus",
        ["Dup.Phase.Folders"] = "Correspondance des dossiers",
        ["Dup.Phase.Verifying"] = "Vérification octet par octet",
        ["Dup.Phase.Finishing"] = "Finalisation",
        ["Dup.Item"] = "élément",
        ["Dup.Items"] = "éléments",
        ["Dup.Folder"] = "dossier",
        ["Dup.FoldersPlural"] = "dossiers",

        // -------------------------------------------------------------- insights
        ["Insights.Title"] = "À regarder de plus près",
        ["Insights.Subtitle"] = "Tout ceci provient de l'analyse déjà effectuée. Rien n'est supprimé sans votre accord.",
        ["Insights.Analyse"] = "Analyser",
        ["Insights.Empty"] = "Rien à signaler. Votre disque est bien rangé.",
        ["Insights.Reclaimable"] = "{0} répartis en {1} groupes",
        ["Insights.StaleFile"] = "Fichiers anciens",
        ["Insights.StaleFileHelp"] = "Gros fichiers inchangés depuis des années. Ancien ne veut pas dire inutile — vérifiez avant de supprimer.",
        ["Insights.EmptyFolder"] = "Dossiers vides",
        ["Insights.EmptyFolderHelp"] = "Dossiers sans aucun contenu, à quelque profondeur que ce soit. Ils ne coûtent pas d'espace, seulement de la clarté.",
        ["Insights.ZeroByteFile"] = "Fichiers vides",
        ["Insights.ZeroByteFileHelp"] = "Fichiers de zéro octet. Parfois des marqueurs qu'un programme attend encore.",
        ["Insights.Junk"] = "Données reconstructibles",
        ["Insights.Items"] = "{0} éléments",
        ["Insights.Warning"] = "DirStat les reconnaît à leur nom et à leur forme, sans interroger le programme qui les a créés. Lisez ce qu'est chaque catégorie avant de supprimer quoi que ce soit, et jamais pendant une compilation ou une installation en cours.",
        ["Insights.WarningTitle"] = "À lire d'abord",
        ["Confidence.Rebuildable"] = "Reconstruit automatiquement",
        ["Confidence.RebuildableHelp"] = "Régénéré à la prochaine utilisation. Supprimer coûte du temps, jamais des données.",
        ["Confidence.Likely"] = "Généralement jetable",
        ["Confidence.LikelyHelp"] = "Presque certainement sans risque, mais un coup d'œil s'impose.",
        ["Confidence.Review"] = "À vérifier",
        ["Confidence.ReviewHelp"] = "Souvent volumineux et souvent indésirable, mais peut être intentionnel.",
        ["Junk.NodeModules"] = "Paquets Node.js (node_modules)",
        ["Junk.BuildOutput"] = "Résultats de compilation",
        ["Junk.PackageCache"] = "Caches de gestionnaires de paquets",
        ["Junk.PythonCache"] = "Caches Python",
        ["Junk.ToolCache"] = "Caches d'outils",
        ["Junk.Temp"] = "Fichiers temporaires",
        ["Junk.Logs"] = "Fichiers journaux",
        ["Junk.Backups"] = "Copies de sauvegarde",
        ["Junk.Installers"] = "Installateurs et images disque",

        // ------------------------------------------------------------- snapshots
        ["Snap.Title"] = "Qu'est-ce qui a changé ?",
        ["Snap.Subtitle"] = "Comparez cette analyse à une autre enregistrée plus tôt pour voir exactement où est passé l'espace.",
        ["Snap.Save"] = "Enregistrer un instantané",
        ["Snap.Saved"] = "Instantané enregistré",
        ["Snap.NoSnapshots"] = "Aucun instantané pour l'instant. Enregistrez-en un maintenant, puis comparez dans quelques jours.",
        ["Snap.Compare"] = "Comparer",
        ["Snap.Taken"] = "Pris le {0}",
        ["Snap.Before"] = "AVANT",
        ["Snap.After"] = "APRÈS",
        ["Snap.Change"] = "ÉCART",
        ["Snap.Grew"] = "A grossi",
        ["Snap.Shrank"] = "A diminué",
        ["Snap.Added"] = "Ajouté",
        ["Snap.Removed"] = "Supprimé",
        ["Snap.NoChanges"] = "Rien n'a changé de plus d'un mégaoctet.",
        ["Snap.Changes"] = "CHANGEMENTS",

        // ------------------------------------------------------------ exclusions
        ["Excl.Title"] = "Règles d'exclusion",
        ["Excl.Subtitle"] = "Noms de dossiers ignorés partout. Utile pour les caches que vous ne voulez jamais compter.",
        ["Excl.Placeholder"] = "Nom de dossier, par exemple node_modules",
        ["Excl.Empty"] = "Aucune exclusion. Tous les dossiers sont analysés.",
        ["Excl.Suggestions"] = "COURANTS",

        ["Insights.Item"] = "{0} élément",

        // --------------------------------------------------------------- families
        ["Family.Video"] = "Vidéo",
        ["Family.Image"] = "Images",
        ["Family.Audio"] = "Audio",
        ["Family.Archive"] = "Archives",
        ["Family.Document"] = "Documents",
        ["Family.Code"] = "Code",
        ["Family.Web"] = "Web",
        ["Family.Executable"] = "Programmes",
        ["Family.Database"] = "Bases de données",
        ["Family.Font"] = "Polices",
        ["Family.DiskImage"] = "Images disque",
        ["Family.System"] = "Système",
        ["Family.Other"] = "Autres",

        // -------------------------------------------------------------- tooltips
        ["Tooltip.Size"] = "Taille",
        ["Tooltip.OnDisk"] = "Sur le disque",
        ["Tooltip.Files"] = "Fichiers",
        ["Tooltip.Directories"] = "Dossiers",
        ["Tooltip.OfParent"] = "Du parent",
        ["Tooltip.Modified"] = "Modifié",
        ["Tooltip.AccessDenied"] = "Accès refusé — le contenu n'est pas inclus.",
        ["Tooltip.Link"] = "Lien — non suivi, sa cible n'est comptée qu'à son emplacement réel.",
        ["Tooltip.HardLink"] = "Lien physique — les octets sont comptés au premier chemin trouvé.",
        ["Tooltip.UnknownSpace"] = "Espace que le volume déclare occupé mais que l'analyse n'a pas pu voir.",
        ["Tooltip.FreeSpace"] = "Espace non alloué sur ce volume.",
        ["Tooltip.Denied"] = "Certains dossiers exigent des droits élevés. Leur contenu apparaît comme espace inconnu.",

        // --------------------------------------------------------------- status
        ["Status.PathCopied"] = "Chemin copié dans le presse-papiers.",
        ["Status.ScanFailed"] = "Échec de l'analyse : {0}",
        ["Status.ScanCancelled"] = "Analyse annulée — résultats partiels affichés.",
        ["Status.Refreshed"] = "{0} réanalysé.",
        ["Status.RefreshFailed"] = "Échec de la réanalyse : {0}",
        ["Status.Exported"] = "Exporté vers {0}",
        ["Status.ExportFailed"] = "Échec de l'export : {0}",
        ["Status.ImageSaved"] = "Vue enregistrée dans {0}",
        ["Status.Deleted"] = "{0} supprimé.",
        ["Status.Trashed"] = "{0} mis à la corbeille.",
        ["Status.PickerFailed"] = "Impossible d'ouvrir le sélecteur de dossiers : {0}",
        ["Status.SaveDialogFailed"] = "Impossible d'ouvrir la boîte d'enregistrement : {0}",
        ["Status.DeniedFolders"] = "{0} dossiers n'ont pas pu être lus",
        ["Status.RecoveredDuplicates"] = "Espace récupéré sur {0} doublons.",
        ["Status.SnapshotSaved"] = "Instantané enregistré dans {0}",
        ["Status.SnapshotFailed"] = "Impossible d'enregistrer l'instantané : {0}",

        // -------------------------------------------------------------- summary
        ["Summary.Scan"] = "{0}  ·  {1} fichiers  ·  {2} dossiers  ·  analysé en {3}",
        ["Summary.OfParent"] = "{0} du parent",
        ["Summary.NFiles"] = "{0} fichiers",
        ["Summary.NFolders"] = "{0} dossiers",
    };
}
