namespace DirStat.App.Localization;

public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> German = new Dictionary<string, string>
    {
        // ---------------------------------------------------------------- common
        ["Common.Cancel"] = "Abbrechen",
        ["Common.Continue"] = "Fortfahren",
        ["Common.Back"] = "Zurück",
        ["Common.Clear"] = "Zurücksetzen",
        ["Common.Apply"] = "Übernehmen",
        ["Common.Add"] = "Hinzufügen",
        ["Common.Remove"] = "Entfernen",
        ["Common.Files"] = "Dateien",
        ["Common.Folders"] = "Ordner",
        ["Common.Name"] = "Name",
        ["Common.Size"] = "Größe",
        ["Common.Share"] = "ANTEIL",
        ["Common.Items"] = "Einträge",
        ["Common.Modified"] = "Geändert",
        ["Common.Dash"] = "—",

        // ---------------------------------------------------------------- window
        ["Window.Theme"] = "Design wechseln",
        ["Window.Language"] = "Sprache",
        ["Window.Minimise"] = "Minimieren",
        ["Window.Maximise"] = "Maximieren",
        ["Window.Close"] = "Schließen",

        // --------------------------------------------------------------- volumes
        ["Volumes.Title"] = "Wo ist Ihr Speicher geblieben?",
        ["Volumes.Subtitle"] = "Wählen Sie ein Laufwerk oder einen Ordner. DirStat erfasst jedes Byte und zeigt, was sich zu löschen lohnt.",
        ["Volumes.Drives"] = "LAUFWERKE",
        ["Volumes.FreeOf"] = "frei von",
        ["Volumes.OrFolder"] = "ODER EIN BESTIMMTER ORDNER",
        ["Volumes.ChooseFolders"] = "Ordner wählen…",
        ["Volumes.ChooseHint"] = "Sie können mehrere auswählen — sie werden gemeinsam analysiert.",
        ["Volumes.Recent"] = "ZULETZT VERWENDET",
        ["Volumes.Compare"] = "Mit einer Momentaufnahme vergleichen",

        // ------------------------------------------------------------------ scan
        ["Scan.Title"] = "Analyse läuft",
        ["Scan.Files"] = "DATEIEN",
        ["Scan.Folders"] = "ORDNER",
        ["Scan.TotalSize"] = "GESAMTGRÖSSE",
        ["Scan.Elapsed"] = "DAUER",
        ["Scan.Throughput"] = "DURCHSATZ",
        ["Scan.CurrentFolder"] = "AKTUELLER ORDNER",
        ["Scan.Cancel"] = "Analyse abbrechen",
        ["Scan.CancelHint"] = "Nach dem Abbrechen wird alles bisher Gefundene angezeigt.",
        ["Scan.FilesPerSecond"] = "{0} Dateien/s",
        ["Scan.Locations"] = "{0} Orte",

        // --------------------------------------------------------------- results
        ["Results.Drives"] = "Laufwerke",
        ["Results.BackToDrives"] = "Zurück zu den Laufwerken",
        ["Results.FilterWatermark"] = "Filter: z. B.  *.mp4  >100mb  after:2025-01-01",
        ["Results.FilterTooltip"] = "Begriffe lassen sich kombinieren: Text sucht in Namen, *.ext sucht Dateitypen,\n>100mb und <1gb begrenzen die Größe, after: und before: das Datum.",
        ["Results.Duplicates"] = "Duplikate",
        ["Results.DuplicatesTooltip"] = "Dateien und Ordner finden, die mehrfach vorhanden sind",
        ["Results.Insights"] = "Analysen",
        ["Results.InsightsTooltip"] = "Alte Dateien, leere Ordner und wiederherstellbare Caches",
        ["Results.ZoomOut"] = "Eine Ebene zurück",
        ["Results.Rescan"] = "Gewählten Ordner neu einlesen (F5)",
        ["Results.Options"] = "Optionen",
        ["Results.Folders"] = "ORDNER",
        ["Results.Treemap"] = "TREEMAP",
        ["Results.Sunburst"] = "RINGDIAGRAMM",
        ["Results.ChartHint"] = "klicken zum Auswählen  ·  Doppelklick zum Hineinzoomen  ·  Pfeiltasten zum Navigieren",
        ["Results.FileTypes"] = "DATEITYPEN",
        ["Results.ClickToIsolate"] = "klicken zum Filtern",
        ["Results.ExportCsv"] = "CSV exportieren",
        ["Results.ExportJson"] = "JSON",
        ["Results.ExportImage"] = "Bild speichern",
        ["Results.ExportImageTooltip"] = "Die aktuelle Ansicht als PNG speichern",
        ["Results.ToggleChart"] = "Zwischen Treemap und Ringdiagramm wechseln",
        ["Results.SaveSnapshot"] = "Momentaufnahme speichern",
        ["Results.SaveSnapshotTooltip"] = "Diese Analyse sichern, um sie später zu vergleichen",
        ["Results.NoExtension"] = "(ohne Endung)",
        ["Results.FreeSpace"] = "Freier Speicher",
        ["Results.UnknownSpace"] = "Unbekannt",

        // ------------------------------------------------------------ context menu
        ["Menu.Open"] = "Öffnen",
        ["Menu.Reveal"] = "Im Dateimanager anzeigen",
        ["Menu.Terminal"] = "Terminal hier öffnen",
        ["Menu.CopyPath"] = "Pfad kopieren",
        ["Menu.ZoomInto"] = "Hineinzoomen",
        ["Menu.Rescan"] = "Diesen Ordner neu einlesen",
        ["Menu.Trash"] = "In den Papierkorb verschieben",
        ["Menu.DeletePermanently"] = "Endgültig löschen…",

        // --------------------------------------------------------------- options
        ["Options.Title"] = "Optionen",
        ["Options.Units"] = "Einheiten wechseln (KiB / KB)",
        ["Options.SizeOnDisk"] = "Größe / belegter Speicher",
        ["Options.Theme"] = "Helles / dunkles Design",
        ["Options.Exclusions"] = "Ausschlussregeln…",
        ["Options.Keyboard"] = "TASTATUR",
        ["Options.Shortcuts"] = "Eingabe — in Ordner hineinzoomen\nRücktaste — hinauszoomen\nPfeiltasten — Ansicht durchlaufen\nStrg+F — Filter aktivieren\nF5 — Auswahl neu einlesen\nEntf — in den Papierkorb\nUmschalt+Entf — endgültig löschen",

        // --------------------------------------------------------------- confirm
        ["Confirm.TrashTitle"] = "In den Papierkorb verschieben?",
        ["Confirm.DeleteTitle"] = "Endgültig löschen?",
        ["Confirm.TrashBody"] = "{0} wird in den Papierkorb verschoben.\n\n{1}",
        ["Confirm.DeleteBody"] = "{0} wird sofort gelöscht. Das lässt sich nicht rückgängig machen.\n\n{1}",
        ["Confirm.AndFiles"] = "{0} mit {1} Dateien",

        // ------------------------------------------------------------- duplicates
        ["Dup.Title"] = "Finden, was doppelt vorhanden ist",
        ["Dup.Subtitle"] = "DirStat vergleicht Inhalte, nicht Namen. Zwei Dateien gelten nur als gleich, wenn jedes Byte übereinstimmt, und zwei Ordner nur, wenn ihre gesamten Bäume übereinstimmen.",
        ["Dup.MinSize"] = "DATEIEN IGNORIEREN, KLEINER ALS",
        ["Dup.MinSizeHint"] = "Kleine Dateien sind ständig doppelt vorhanden und bringen kaum Speicher zurück.",
        ["Dup.Verify"] = "Nach dem Vergleich Byte für Byte prüfen",
        ["Dup.VerifyHint"] = "Liest jedes bestätigte Duplikat ein zweites Mal. Der 128-Bit-Inhaltshash macht eine falsche Übereinstimmung bereits verschwindend unwahrscheinlich.",
        ["Dup.Find"] = "Duplikate suchen",
        ["Dup.SearchAgain"] = "Erneut suchen",
        ["Dup.ExpandAll"] = "Alle aufklappen",
        ["Dup.Collapse"] = "Zuklappen",
        ["Dup.EmptyTitle"] = "Hier ist nichts doppelt",
        ["Dup.EmptyFiles"] = "Keine doppelten Dateien oberhalb der Mindestgröße.",
        ["Dup.EmptyFolders"] = "Keine doppelten Ordner. Ordner stimmen nur überein, wenn ihr gesamter Inhalt übereinstimmt.",
        ["Dup.Keep"] = "Behalten",
        ["Dup.Oldest"] = "Älteste",
        ["Dup.Newest"] = "Neueste",
        ["Dup.ShortestPath"] = "Kürzester Pfad",
        ["Dup.KeepOldestTip"] = "Alle Kopien außer der ältesten jeder Gruppe markieren",
        ["Dup.KeepNewestTip"] = "Alle Kopien außer der neuesten jeder Gruppe markieren",
        ["Dup.KeepShortestTip"] = "Alle Kopien außer der obersten im Verzeichnisbaum markieren",
        ["Dup.MoveToTrash"] = "Markierte in den Papierkorb",
        ["Dup.NothingSelected"] = "Nichts markiert",
        ["Dup.Selected"] = "{0} markiert  ·  {1} zurückzugewinnen",
        ["Dup.Copies"] = "{0} Kopien",
        ["Dup.Recoverable"] = "zurückzugewinnen",
        ["Dup.Summary"] = "{0} zurückzugewinnen  ·  {1} Gruppen  ·  {2} gelesen in {3}",
        ["Dup.NoneFound"] = "Keine Duplikate gefunden  ·  gesucht in {0}",
        ["Dup.Cancelled"] = "Suche abgebrochen — Teilergebnis wird angezeigt.",
        ["Dup.StaleTotals"] = "Die Summen sind nach dem Entfernen veraltet — bitte erneut suchen.",
        ["Dup.ConfirmTitle"] = "Duplikate in den Papierkorb verschieben?",
        ["Dup.ConfirmBody"] = "{0} werden in den Papierkorb verschoben und geben {1} frei.\n\nVon jeder Gruppe bleibt immer eine Kopie erhalten.",
        ["Dup.FilesTab"] = "Dateien  ({0})",
        ["Dup.FoldersTab"] = "Ordner  ({0})",
        ["Dup.NFiles"] = "{0} Dateien",
        ["Dup.Candidates"] = "{0} Kandidaten",
        ["Dup.BytesRead"] = "{0} gelesen",
        ["Dup.Moved"] = "{0} in den Papierkorb verschoben, {1} freigegeben.",
        ["Dup.MovedPartial"] = "{0} verschoben; {1} konnten nicht entfernt werden.",
        ["Dup.Phase.Grouping"] = "Nach Größe gruppieren",
        ["Dup.Phase.Screening"] = "Kandidaten vorprüfen",
        ["Dup.Phase.Hashing"] = "Inhalte vergleichen",
        ["Dup.Phase.Folders"] = "Ordner abgleichen",
        ["Dup.Phase.Verifying"] = "Byte für Byte prüfen",
        ["Dup.Phase.Finishing"] = "Abschließen",
        ["Dup.Item"] = "Eintrag",
        ["Dup.Items"] = "Einträge",
        ["Dup.Folder"] = "Ordner",
        ["Dup.FoldersPlural"] = "Ordner",

        // -------------------------------------------------------------- tooltips
        ["Tooltip.Size"] = "Größe",
        ["Tooltip.OnDisk"] = "Belegt",
        ["Tooltip.Files"] = "Dateien",
        ["Tooltip.Directories"] = "Ordner",
        ["Tooltip.OfParent"] = "Vom Ordner",
        ["Tooltip.Modified"] = "Geändert",
        ["Tooltip.AccessDenied"] = "Zugriff verweigert — der Inhalt ist nicht enthalten.",
        ["Tooltip.Link"] = "Verknüpfung — wird nicht verfolgt, das Ziel zählt nur an seinem tatsächlichen Ort.",
        ["Tooltip.HardLink"] = "Harte Verknüpfung — die Bytes werden beim zuerst gefundenen Pfad gezählt.",
        ["Tooltip.UnknownSpace"] = "Speicher, den das Laufwerk als belegt meldet, den die Analyse aber nicht sehen konnte.",
        ["Tooltip.FreeSpace"] = "Nicht belegter Speicher auf diesem Laufwerk.",
        ["Tooltip.Denied"] = "Einige Ordner erfordern erweiterte Rechte. Ihr Inhalt erscheint als unbekannter Speicher.",

        // --------------------------------------------------------------- status
        ["Status.PathCopied"] = "Pfad in die Zwischenablage kopiert.",
        ["Status.ScanFailed"] = "Analyse fehlgeschlagen: {0}",
        ["Status.ScanCancelled"] = "Analyse abgebrochen — Teilergebnis wird angezeigt.",
        ["Status.Refreshed"] = "{0} neu eingelesen.",
        ["Status.RefreshFailed"] = "Neu einlesen fehlgeschlagen: {0}",
        ["Status.Exported"] = "Exportiert nach {0}",
        ["Status.ExportFailed"] = "Export fehlgeschlagen: {0}",
        ["Status.ImageSaved"] = "Ansicht gespeichert unter {0}",
        ["Status.Deleted"] = "{0} gelöscht.",
        ["Status.Trashed"] = "{0} in den Papierkorb verschoben.",
        ["Status.PickerFailed"] = "Ordnerauswahl konnte nicht geöffnet werden: {0}",
        ["Status.SaveDialogFailed"] = "Speicherdialog konnte nicht geöffnet werden: {0}",
        ["Status.DeniedFolders"] = "{0} Ordner konnten nicht gelesen werden",
        ["Status.RecoveredDuplicates"] = "Speicher aus {0} Duplikaten zurückgewonnen.",
        ["Status.SnapshotSaved"] = "Momentaufnahme gespeichert unter {0}",
        ["Status.SnapshotFailed"] = "Momentaufnahme konnte nicht gespeichert werden: {0}",

        // -------------------------------------------------------------- summary
        ["Summary.Scan"] = "{0}  ·  {1} Dateien  ·  {2} Ordner  ·  analysiert in {3}",
        ["Summary.OfParent"] = "{0} vom Ordner",
        ["Summary.NFiles"] = "{0} Dateien",
        ["Summary.NFolders"] = "{0} Ordner",
    };
}
